#!/usr/bin/env python3
"""PHP-equivalent CTAGS / flow extractor for FA 2.4.3"""
import os, re

root = "/home/kevin/Documents/ksf_Infrastructure/FA/2.4.3"
out = os.path.expanduser("~/Documents/FA_Ctags_Flows.md")

func_re = re.compile(r'function\s+(\w+)\s*\(')
include_re = re.compile(r'(include|require)_once?\(["\']([^"\']+)["\']\)')
db_call_re = re.compile(r'db_query\s*\(')

flows = {}

for dirpath, dirs, files in os.walk(root):
    for f in files:
        if not f.endswith('.php'):
            continue
        path = os.path.join(dirpath, f)
        rel = os.path.relpath(path, root)
        try:
            with open(path, 'r', errors='ignore') as file:
                lines = file.read().splitlines()
        except Exception:
            continue
        for i, line in enumerate(lines, 1):
            m = func_re.search(line)
            if m:
                fname = m.group(1)
                flows.setdefault(fname, []).append({"file": rel, "line": i, "type": "function"})
            inc = include_re.search(line)
            if inc:
                target = inc.group(2)
                flows.setdefault(rel, []).append({"file": rel, "line": i, "type": "include", "target": target})
            if db_call_re.search(line):
                flows.setdefault("db_query", []).append({"file": rel, "line": i, "type": "db_call"})

with open(out, 'w') as f:
    f.write("# FA 2.4.3 PHP Flow / CTAGS Equivalent\n\n")
    f.write("Generated by `extract_fa_flows.py`\n\n")
    for name, refs in sorted(flows.items()):
        f.write(f"## `{name}`\n\n")
        for r in refs:
            if r.get("type") == "include":
                f.write(f"- `{r['file']}:{r['line']}` include `{r.get('target')}`\n")
            elif r.get("type") == "db_call":
                f.write(f"- `{r['file']}:{r['line']}` db_call\n")
            else:
                f.write(f"- `{r['file']}:{r['line']}` function def\n")
        f.write("\n")

print(f"Wrote flows to {out} ({len(flows)} symbols)")
