@startuml
title Detailed Logic Flow - customers
start
:Entry customers;
:Load session/auth;
:Include db_pager.inc");;
:Include session.inc");;
:Include date_functions.inc");;
:Include banking.inc");;
:Include ui.inc");;
:Include contacts_view.inc");;
if ($SysPrefs->use_popup_windows)) then (yes)
  :Evaluate condition;
else (no)
  :Skip $SysPrefs->use_popup;
endif
if (user_use_date_picker())) then (yes)
  :(user_use_date_picker());
else (no)
  :Skip user_use_date_picker;
endif
if (isset($_GET['debtor_no']))) then (yes)
  :(isset());
else (no)
  :Skip isset($_GET['debtor_;
endif
if (strlen($_POST['CustName']) == 0)) then (yes)
  :(strlen());
else (no)
  :Skip strlen($_POST['CustN;
endif
if (strlen($_POST['cust_ref']) == 0)) then (yes)
  :(strlen());
else (no)
  :Skip strlen($_POST['cust_;
endif
if (!check_num('credit_limit', 0))) then (yes)
  :(check_num());
else (no)
  :Skip !check_num('credit_l;
endif
if (!check_num('pymt_discount', 0, 100))) then (yes)
  :(check_num());
else (no)
  :Skip !check_num('pymt_dis;
endif
if (!check_num('discount', 0, 100))) then (yes)
  :(check_num());
else (no)
  :Skip !check_num('discount;
endif
:(can_process());
:(handle_submit());
:Output (form / display / data);
stop
@enduml
