@startuml
title Detailed Logic Flow - suppliers
start
:Entry suppliers;
:Load session/auth;
:Include db_pager.inc");;
:Include session.inc");;
:Include ui.inc");;
:Include contacts_view.inc");;
if ($SysPrefs->use_popup_windows)) then (yes)
  :Evaluate condition;
else (no)
  :Skip $SysPrefs->use_popup;
endif
if (user_use_date_picker())) then (yes)
  :(user_use_date_picker());
else (no)
  :Skip user_use_date_picker;
endif
if (isset($_GET['supplier_id']))) then (yes)
  :(isset());
else (no)
  :Skip isset($_GET['supplie;
endif
if ($supplier_id)) then (yes)
  :Evaluate condition;
else (no)
  :Skip $supplier_id);
endif
if ($supplier_id && !is_new_supplier($supplier_id) && ) then (yes)
  :(is_new_supplier());
else (no)
  :Skip $supplier_id && !is_;
endif
if (is_new_supplier($supplier_id))) then (yes)
  :(is_new_supplier());
else (no)
  :Skip is_new_supplier($sup;
endif
if (!$supplier_id) table_section(2)) then (yes)
  :(table_section());
else (no)
  :Skip !$supplier_id) table;
endif
if (!$supplier_id) {) then (yes)
  :Evaluate condition;
else (no)
  :Skip !$supplier_id) {;
endif
:(supplier_settings());
:Output (form / display / data);
stop
@enduml
